### ISSUE TITLE
Error: expected type-specifier before ‘codecvt_utf8’ ？

### ISSUE THREAD

**Issue by colynhn** [AtheS21/SymspellCPP#2]
hello, the error above occur when I use #define UNICODE_SUPPORT and run the program; there is no codecvt in the system include ,so how to fix it?
system: linux 
gcc version: 4.8.5

thanks

**Comment by AtheS21** [comment]
Hi, unfortunately codecvt is only available on gcc 5 onward.

Basically I only use it to read dictionary files with other encodings so if you absolutely have to use gcc 4.8 then 1 solution is that you can rewrite the loading section so that the dictionary from your encoding can be loaded properly, after that it should work normally. 

If you are using utf-8 as the encoding then it should be easy but other encoding might be tricky.
Hope it helps

**Comment by colynhn** [comment]
when reading a utf-8 file,  I use ifstream to get string , then convert to wstring , but it needs a conversion step, Is there a better and more directly way?

thanks

**Comment by AtheS21** [comment]
Yes you can use wifstream directly, it will read the file into wstring for you.

**Comment by colynhn** [comment]
thank you so much , i will close this issue.
