### ISSUE TITLE
Question about Japanese

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [AtheS21/SymspellCPP#3]
Hello, 
The author of SymSpell mentioned that you've done some testing for Japanese.
https://github.com/wolfgarbe/SymSpell/discussions/108

If it's okay, may I ask about how was your experience with using SymSpell for Japanese? Were results satisfying? 
There is very little mentioning of applying edit-distance approaches for it due to its specifics. 
Thanks in advance.

**Comment by AtheS21** [comment]
Unfortunately, the test I did was just to confirm that the ported version can produce the same output as the original code, I didn't design the test data with any application in mind since I was just helping out and wasn't in charge at the time, so even though I'd say the code performs well enough, I'm not sure how good it is when deploying on a real application. Im afraid you will probably need to try applying Symspell into your problem and evaluate its effectiveness yourself

**Comment by aTan-aka-Xellos** [comment]
I see, thank you for your answer.
